fix: search form cards structure
MovingBlocks/ModuleSite pull request #52
Opened 2021-04-16 15:30 UTC by ryuk156

Screenshot: 
![image](https://user-images.githubusercontent.com/49101492/115047991-b756e200-9ef6-11eb-9fc8-fdbef1031543.png)

2021-04-17 05:06 UTC, majordwarf commented
I guess this PR only deals with the cards of the blog page but since we are focusing on cards in this PR, I'd like to see proper structuring. 

Example: The module page shows the following card because there is no description available. 
![image](https://user-images.githubusercontent.com/23737560/115102474-a34bc880-9f68-11eb-9cce-a02214c27336.png)

Instead of just focusing on search form cards, we should focus on all the cards (probably make the card as a component?)

2021-04-17 13:30 UTC, ryuk156 commented
> I guess this PR only deals with the cards of the blog page but since we are focusing on cards in this PR, I'd like to see proper structuring.
> 
> Example: The module page shows the following card because there is no description available.
> ![image](https://user-images.githubusercontent.com/23737560/115102474-a34bc880-9f68-11eb-9cce-a02214c27336.png)
> 
> Instead of just focusing on search form cards, we should focus on all the cards (probably make the card as a component?)
> Making cards a component would provide us a single source of truth to modify all the cards instead of changing code in multiple places.

I will have a look at this and try to make it a different component

2021-04-24 18:11 UTC, jdrueckert requested changes
I noted two things:
1. I don't see any preview texts: (this is the same for the module search by the way)
![grafik](https://user-images.githubusercontent.com/29981695/115968578-ded22e00-a538-11eb-873a-d00fe251fdc2.png)

2. Clicking on "Next Page" will drop the search param, so if there's more search results than can be displayed on one page, you'll not be able to see the rest that's not displayed on the first page.
Related, I just noticed, that it actually showed me the 12 search results on the first page, but still showed me the "Next Page" button. It even also shows me a "Previous Page" button, if I enter something in the search field while on the second page of blog entries.
This does not happen with the modules, but I guess that's due to there not yet being so many that we need multiple pages.

2021-04-24 18:11 UTC, jdrueckert commented on modules/Gooey Example/index.md
> +No information available for this module.The information will be available in upcoming updates. You can have more details about this module [here](https://github.com/Terasology)
```suggestion
Currently, there's no information available for this module. Please, refer to the method repo in [here](https://github.com/Terasology) for details.
```

2021-04-24 18:11 UTC, jdrueckert commented on src/components/SearchResult/SearchResult.jsx
> +        {results.length > 1 && "modules matching with"} "{query}"
if the only thing changing depending on the number of results, should we only make the "module" / "modules" part of the string depend on it and separate the "matching with" part as that stays the same?

2021-04-25 06:45 UTC, ryuk156 commented
> I noted two things:
> 
> 1. I don't see any preview texts: (this is the same for the module search by the way)
>    ![grafik](https://user-images.githubusercontent.com/29981695/115968578-ded22e00-a538-11eb-873a-d00fe251fdc2.png)
> 2. Clicking on "Next Page" will drop the search param, so if there's more search results than can be displayed on one page, you'll not be able to see the rest that's not displayed on the first page.
>    Related, I just noticed, that it actually showed me the 12 search results on the first page, but still showed me the "Next Page" button. It even also shows me a "Previous Page" button, if I enter something in the search field while on the second page of blog entries.
>    This does not happen with the modules, but I guess that's due to there not yet being so many that we need multiple pages.

For me, it is working fine for the blog and in the module, I forgot to fetch an excerpt will fix that in the next push
![image](https://user-images.githubusercontent.com/49101492/115983610-dcff7d80-a5bf-11eb-865d-9f3df1cc8cb6.png)


Talking about "Next" and "Previous" thing this PR only focuses on make a card as a separate component will be fixing that in the next PR

2021-04-25 06:52 UTC, ryuk156 commented
@jdrueckert Updated the PR Please have a look

2021-04-25 06:53 UTC, ryuk156 commented on modules/Gooey Example/index.md
> +No information available for this module.The information will be available in upcoming updates. You can have more details about this module [here](https://github.com/Terasology)
done

2021-05-14 19:01 UTC, jdrueckert commented
Unfortunately, it's still not working for me :thinking: 
I do see the preview texts if I don't filter:
![image](https://user-images.githubusercontent.com/29981695/118316739-781cb080-b4f7-11eb-8231-40189d55ebf2.png)
But as soon as I type in a letter for filtering, they disappear:
![image](https://user-images.githubusercontent.com/29981695/118316805-908ccb00-b4f7-11eb-8c47-66c3a0d92df4.png)

2021-06-16 15:29 UTC, closed without merging